# Generated by Django 4.0.2 on 2022-02-10 18:30

from django.db import migrations, models
import petsatgram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='media/', validators=[petsatgram.main.validators.validate_file_size], verbose_name=''),
        ),
    ]
