# Generated by Django 4.0.2 on 2022-02-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_petphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
