# Generated by Django 4.0.2 on 2022-02-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_picture_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(verbose_name='Link to profile picture'),
        ),
    ]
